backend:
  name: "github"
  repo: "schalkventer/pocket-reporter"
media_folder: "static/assets"
public_folder: "assets"
editor:
   preview: false
collections:
  - name: "referencePage"
    label: "Reference Page"
    folder: "src/data/reference/"
    create: true
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "referenceList"
        label: "Reference List"
        widget: "list"
        required: false
        field:
          name: "reference"
          label: "Reference"
          widget: "relation"
          collection: "itemCollection"
          searchFields: [ "title" ]
          valueField: "title"
  - name: "itemCollection"
    label: "Item"
    folder: "src/data/items/"
    create: true
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
        required: true
      - name: "text"
        label: "Text"
        widget: "string"